### PR TITLE
fixed sets

### PR DESCRIPTION
**Pull request by tooomm**
I realized that there are incomplete sets shown in the `edit sets` dialog:
missing set info tokens
A short search showed that they come from your tokens.xml file!
None of these sets show up in mtgjson or on gatherer...

What I could find about them:
- FNM: promotional flip Token for Friday Night Magic<br>
(http://archive.wizards.com/Magic/magazine/article.aspx?x=mtg/daily/arcana/938)
- Avacyn Restored (The Helvault Experience): some kind of promotional pre release token prizes for Avacyn Restored<br>
(http://mtgsalvation.gamepedia.com/Token#Double-faced_tokens)<br>
(http://archive.wizards.com/Magic/magazine/article.aspx?x=mtg/daily/arcana/963)
- League: promotional token prizes for in-store leagues for different sets<br>(http://mtgsalvation.gamepedia.com/League)

http://magiccards.info/extras.html

Suggestions:
- change all of the *special sets* above in your file to promotional sets, since they are promotional (e.g. `FNM` to `pFNM`)<br>

There is a set for Friday Night Magic promo cards (pFNM) already in mtgjson.
This will at least make the `FNM` set disappear.

Since you do not provide additional information in your file about the sets, Oracle doesn't know about them and can't include this information in the cards.xml.

I found out that there are sets information in cards.xml... maybe we can include them in the token.xml as well... and it worked! :+1:
```
    <sets>
        <set>
            <name>ARH</name>
            <longname>Avacyn Restored (The Helvault Experience)</longname>
            <settype>Promo</settype>
            <releasedate>2012-04-28</releasedate> (i put the pre-release date from avacayn restored here!)
        </set>
        <set>
            <name>LGE</name>
            <longname>League</longname>
            <settype>Promo</settype>
            <releasedate>2012-07-13</releasedate> (i put the release date of m13 here, since that was the start of this tournament types)
        </set>
    </sets>
```

after the change (i didn't add the small p's already for the pic)
fixed tokens

### CODE REVIEW

**Comment by tooomm** [comment]
Maybe you want to tell the user that they are artificial sets and no real sets somehow...

- use "Token" instead of "Promo" as settype would work for example
- use `tFNM`, `tLGE` and `tARH` instead the small p
this would separate the sets better from normal/real sets

**Comment by tooomm** [comment]
selfnote:
- need to fix example set (one <set> too much)

**Comment by Psithief** [comment]
Those tokens were in the file before I started working on it, so if they cause trouble then I'm inclined to just comment them out.

The Avacyn Restored one might belong to `pREL` *Release Events* or `pLPA` Launch Parties.

@Sembiance 
What would the mtgjson set code for these would be if those 'sets' used your conventions?

**Comment by tooomm** [comment]
*Avacyn Restored (The Helvault Experience)* fits nicely to the `pPRE` set
(not *pREL* ! it's was a pre-release special as you can read in my first post, no release special)

I wasn't sure about `pLPA` exactly... but hey:
http://archive.wizards.com/Magic/magazine/article.aspx?x=mtg/daily/feature/181a
Launch Parties = former Release Events (not Pre-Release!)
(there are mentions about the "store League" as well in the article!)

So just the *League* 'set' needs to get resolved...

**Comment by Psithief** [comment]
This PR can't be merged because:
* It is out of date.
* I don't want to put <set> tags in the file.
* I didn't like the arbitrary white-space changes.

**Pull request closed without merging**
